### ISSUE TITLE
ffmpeg won't auto-download for Apple Silicon Mac

### ISSUE THREAD

**Issue by GIP2000** [nathanbabcock/ffmpeg-sidecar#15] opened 2023-07-31 15:54 UTC
When running the auto-download for ffmpeg on an M1 mac it fails because its not compatible with non x86 architectures. Is there a way to add it?

**Comment by nathanbabcock** [comment] 2023-08-07 03:05
I'd absolutely be open to a pull request for this if you're up for it.

I found this website for OSX M1 binaries: http://www.osxexperts.net/. Other projects such as [`ffmpeg-static` use this as their source](https://github.com/eugeneware/ffmpeg-static/issues/49).

**Comment by paulrouget** [comment] 2023-08-07 10:14
I'm maintaining home made builds of static ffmpeg builds here: https://github.com/mi-g/ffmpeg-static-builder/releases

These are not builds gathered from all over the place. They are all built statically, with the same dependencies, and tested.
Might be a better fit for ffmpeg-sidecar's download feature.

I'm just missing a Mac Intel build (need access to a older Mac to do that).

This is part of a bigger project and it's supposed to be maintained long term (years).

**Comment by jt-wang** [comment] 2023-09-15 23:03
Thanks @nathanbabcock for building this project! auto-download for Apple Silicon would be great! 

I'd like to introduce https://github.com/nathanbabcock/ffmpeg-sidecar/ to https://github.com/jt-wang/whisper-ui which highly depends on `ffmpeg` and `ffprobe` to read audio files. Currently, without auto-downloading for Apple Silicon, to build `whisper-ui`, I have to manually download these two dependencies, and use `Command.sidecar` to execute the shell command.

**Comment by nathanbabcock** [comment] 2023-09-17 21:31
Okay, let's give it a try.

PR #16 aims to add ffmpeg auto-download support for the Mac M1 chipset.

Since I don't have one to test on, someone will need to verify that it works as expected. This could be as simple as:

```bash
git checkout feat/mac-m1
cargo run --example download_ffmpeg
```

**Comment by nathanbabcock** [comment] 2023-10-09 22:06
This is now fixed with Github Actions in place to verify the download behavior across Mac, Mac M1, and Linux (I'll cover Windows testing on my local environment). It also caught a regression in the regular Mac download archive format that changed from FFmpeg v5 -> v6.

**Closed** 2023-10-09 22:06 UTC
